CREATE DATABASE [ClinicaBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClinicaBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ClinicaBD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClinicaBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ClinicaBD_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ClinicaBD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClinicaBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClinicaBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClinicaBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClinicaBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClinicaBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClinicaBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClinicaBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClinicaBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClinicaBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClinicaBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClinicaBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClinicaBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClinicaBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClinicaBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClinicaBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClinicaBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ClinicaBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClinicaBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClinicaBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClinicaBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClinicaBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClinicaBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ClinicaBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClinicaBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ClinicaBD] SET  MULTI_USER 
GO

ALTER DATABASE [ClinicaBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClinicaBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClinicaBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClinicaBD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ClinicaBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ClinicaBD] SET  READ_WRITE 
GO


USE [ClinicaBD]
GO

/****** Object:  Table [dbo].[Especialidad]    Script Date: 3/07/2020 10:28:16 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Especialidad](
	[IdEspecialidad] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Especialidad] PRIMARY KEY CLUSTERED 
(
	[IdEspecialidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Doctor](
	[IdDoctor] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [nvarchar](50) NULL,
	[IdEspecialidad] [int] NOT NULL,
	[NumCredencial] [nvarchar](10) NOT NULL,
	[Hospital] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_Doctor] PRIMARY KEY CLUSTERED 
(
	[IdDoctor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Doctor]  WITH CHECK ADD  CONSTRAINT [FK_Doctor_Especialidad_IdEspecialidad] FOREIGN KEY([IdEspecialidad])
REFERENCES [dbo].[Especialidad] ([IdEspecialidad])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Doctor] CHECK CONSTRAINT [FK_Doctor_Especialidad_IdEspecialidad]
GO

/****** Object:  Table [dbo].[Paciente]    Script Date: 3/07/2020 10:30:43 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Paciente](
	[IdPaciente] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [nvarchar](50) NOT NULL,
	[NumDocumento] [nvarchar](10) NOT NULL,
	[NumSeguroSocial] [nvarchar](10) NOT NULL,
	[Direccion] [nvarchar](100) NULL,
	[TelContacto] [nvarchar](10) NOT NULL,
	[CodPostal] [nvarchar](8) NULL,
	[Email] [nvarchar](20) NULL,
 CONSTRAINT [PK_Paciente] PRIMARY KEY CLUSTERED 
(
	[IdPaciente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[PacienteXDoctor]    Script Date: 3/07/2020 10:31:06 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PacienteXDoctor](
	[IdPacienteXDoctor] [int] IDENTITY(1,1) NOT NULL,
	[IdPaciente] [int] NOT NULL,
	[IdDoctor] [int] NOT NULL,
 CONSTRAINT [PK_PacienteXDoctor] PRIMARY KEY CLUSTERED 
(
	[IdPacienteXDoctor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PacienteXDoctor]  WITH CHECK ADD  CONSTRAINT [FK_PacienteXDoctor_Doctor_IdDoctor] FOREIGN KEY([IdDoctor])
REFERENCES [dbo].[Doctor] ([IdDoctor])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PacienteXDoctor] CHECK CONSTRAINT [FK_PacienteXDoctor_Doctor_IdDoctor]
GO

ALTER TABLE [dbo].[PacienteXDoctor]  WITH CHECK ADD  CONSTRAINT [FK_PacienteXDoctor_Paciente_IdPaciente] FOREIGN KEY([IdPaciente])
REFERENCES [dbo].[Paciente] ([IdPaciente])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PacienteXDoctor] CHECK CONSTRAINT [FK_PacienteXDoctor_Paciente_IdPaciente]
GO


INSERT INTO Especialidad VALUES('Medicina General');
INSERT INTO Especialidad VALUES('Pediatria');
INSERT INTO Especialidad VALUES('Maternidad');
INSERT INTO Especialidad VALUES('Psicología');
INSERT INTO Especialidad VALUES('Odontología');